version: '2.1'

services:
  bikeroutes-db:
    image: mongo
    ports:
        - 7002:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_HOST=bikeroutes-db
    volumes:
      - /data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null --quiet
  bikeroutes-ms:
    build: .
    command: sails lift --verbose --port 6002
    ports:
      - "6002:6002"
    depends_on:
      - bikeroutes-db